{% set name = "jina-hubble-sdk" %}
{% set version = "0.39.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jina-hubble-sdk-{{ version }}.tar.gz
  sha256: 9021417794a6d3cf3fad8a880cf668a3a986b9d53d5be5fa391aae1767a5b9b0

build:
  entry_points:
    - jina-auth=hubble.__main__:main
    - jina-hub=hubble.executor.__main__:main
    - docker-credential-jina-hubble=hubble.dockerauth:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=18.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - aiohttp
    - rich
    - importlib-metadata
    - filelock
    - pathspec
    - cryptography
    - docker-py
    - pyyaml

test:
  imports:
    - hubble
  commands:
    - pip check
    - jina-auth --help
    - jina-hub --help
    - docker-credential-jina-hubble --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jina-ai/jina-hubble-sdk/
  summary: SDK for Hubble API at Jina AI.
  dev_url: https://github.com/jina-ai/jina-hubble-sdk/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mapleeit
    - nomagick
    - delgermurun
    - Andrei997
    - floralatin
